GET http://127.0.0.1:3005 HTTP/1.1
Content-type:application/json

### Users
GET http://127.0.0.1:8080/users HTTP/1.1
Content-type:application/json

### GET Users/:account
GET http://127.0.0.1:8080/users/0x0000000000000000000000000000000000000000000000000000000000000000 HTTP/1.1
Content-type:application/json

### POST /users
POST http://127.0.0.1:8080/users HTTP/1.1
Content-type:application/json

{"account":"0x521DB21B0b92aBEDd35508FBd0798e4669489dFE"}

# response
# {
#     "p_image": "public/uploads/p_image-1690852716803-415628723.png"
# }

### proposal
GET http://127.0.0.1:8080/proposal?page=1&limit=10 HTTP/1.1
Content-type:application/json

### proposal pinata
POST http://127.0.0.1:8080/proposal/pinata HTTP/1.1
Authorization: Bearer 0x521DB21B0b92aBEDd35508FBd0798e4669489dFE
Content-type:application/json

### posts
GET http://127.0.0.1:8080/posts HTTP/1.1
Content-type:application/json

### Proposal/ipfs
GET http://127.0.0.1:8080/proposal/ipfs HTTP/1.1
Content-type:application/json

{
    "IpfsHash":"QmX1L3keRQusuQbjZyG31AQYu4zUyvuxT4zfNpoTSjPQsA"
}